### ISSUE TITLE
java.lang.IllegalArgumentException: Key "ton" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.

### ISSUE THREAD

**Issue by gemcoder21** [gemwalletcom/core#340]
``````
type: crash
osVersion: google/sargo/sargo:12/SP2A.220505.008/2023020600:user/release-keys
package: com.gemwallet.android:496
process: com.gemwallet.android
processUptime: 2020 ms

java.lang.IllegalArgumentException: Key "ton" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SourceFile:28)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(Unknown Source:2)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(Unknown Source:33)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1$measuredItemProvider$1.getAndMeasure-0kLqBqw(Unknown Source:20)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(Unknown Source:873)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(Unknown Source:19)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(Unknown Source:65)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:38)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(Unknown Source:0)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(Unknown Source:98)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(Unknown Source:8)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Unknown Source:112)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:51)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:130)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:133)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(Unknown Source:17)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(Unknown Source:16)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(Unknown Source:7)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(Unknown Source:139)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(Unknown Source:87)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(Unknown Source:33)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(Unknown Source:14)
	at android.view.View.draw(View.java:22707)
	at android.view.View.updateDisplayListIfDirty(View.java:21579)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4531)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4251)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3374)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8793)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:780)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```
This paste expires in <1 day. Public IP access. Share whatever you see with others in seconds with [Context](https://ctxt.io/).[Terms of Service](https://ctxt.io/tos)[Report this](https://ctxt.io/2/AAB4EYFWEQ#)

**Comment by Mojiaction** [comment]
type: crash
osVersion: google/sargo/sargo:12/SP2A.220505.008/2023020600:user/release-keys
package: com.gemwallet.android:496
process: com.gemwallet.android
processUptime: 2020 ms

java.lang.IllegalArgumentException: Key "ton" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SourceFile:28)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(Unknown Source:2)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(Unknown Source:33)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1$measuredItemProvider$1.getAndMeasure-0kLqBqw(Unknown Source:20)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(Unknown Source:873)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(Unknown Source:19)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(Unknown Source:65)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:38)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(Unknown Source:0)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(Unknown Source:98)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(Unknown Source:8)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Unknown Source:112)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:51)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:130)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:133)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(Unknown Source:17)
	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(Unknown Source:16)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(Unknown Source:7)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(Unknown Source:139)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(Unknown Source:87)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(Unknown Source:33)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(Unknown Source:14)
	at android.view.View.draw(View.java:22707)
	at android.view.View.updateDisplayListIfDirty(View.java:21579)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4531)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4251)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3374)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8793)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:780)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```
